/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#e5eadc',
        'primary': '#236d00',
        'surface-bright': '#f6fbec',
        'outline': '#707a68',
        'on-error': '#ffffff',
        'surface-muted': '#F4F6F8',
        'on-secondary-fixed-variant': '#303f91',
        'secondary-fixed-dim': '#bac3ff',
        'error': '#ba1a1a',
        'inverse-on-surface': '#edf3e4',
        'primary-container': '#5cb338',
        'tertiary-container': '#fb6db3',
        'primary-fixed-dim': '#82dc5c',
        'inverse-primary': '#82dc5c',
        'secondary-container': '#97a5fe',
        'on-tertiary-container': '#6e0044',
        'on-surface-variant': '#404a3a',
        'on-primary': '#ffffff',
        'secondary': '#4958ab',
        'sky-blue': '#0091D2',
        'on-background': '#181d14',
        'on-tertiary-fixed-variant': '#8a0857',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#00105c',
        'outline-variant': '#bfcab5',
        'surface-container-highest': '#dfe5d6',
        'on-secondary-container': '#283789',
        'tertiary-fixed-dim': '#ffafd0',
        'leaf-green': '#5CB338',
        'on-primary-fixed': '#062100',
        'primary-fixed': '#9df975',
        'secondary-fixed': '#dee0ff',
        'surface-variant': '#dfe5d6',
        'error-container': '#ffdad6',
        'surface-container': '#eaf0e1',
        'deep-ocean': '#2B3A8C',
        'surface': '#f6fbec',
        'surface-dim': '#d6dcce',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'warm-accent': '#FF7000',
        'on-primary-container': '#113f00',
        'surface-tint': '#236d00',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ffd8e6',
        'surface-container-low': '#f0f6e7',
        'on-surface': '#181d14',
        'tertiary': '#a92a70',
        'inverse-surface': '#2c3228',
        'on-primary-fixed-variant': '#195200',
        'background': '#f6fbec',
        'on-tertiary-fixed': '#3d0024',
        'on-tertiary-container': '#6e0044',
        'secondary-container': '#97a5fe',
        'tertiary-fixed-dim': '#ffafd0',
        'on-secondary-container': '#283789',
        'on-secondary-fixed': '#00105c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        gutter: '24px',
        'section-padding': '80px',
        'container-max': '1200px',
        base: '8px',
      },
      fontFamily: {
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Be Vietnam Pro', 'sans-serif'],
        'body-md': ['Be Vietnam Pro', 'sans-serif'],
        'body-lg': ['Be Vietnam Pro', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
}
